[package]
name = "metaxbridge"
version = "0.0.0"

[addresses]
metaxbridge = "18c5af3d8794889112ae5665a684f79639a3a253ec6a87562ceb9ac99e1095dd"
mpcManager = "18c5af3d8794889112ae5665a684f79639a3a253ec6a87562ceb9ac99e1095dd"

[dependencies]
cbridge_adapter = {local = "./adapters/cbridge_adapter"}
metaxtrade = {local = "./interface/metaxtrade"}

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib/"
rev = 'mainnet'