[package]
name = "dexrouter"
version = "2.0.2"

[addresses]
dexrouter = "0x7eabd7afead571da80e71bc6d7237102316767f3b617b4efed2dfa04e0ccc2ac"
deployer = "0xee873ef31945011c4cb684ebeab858cb4cb8a62595b4013a57cd8c6285d2b9a5"

[dependencies]
pontem_adapter =  {local = "./adapters/pontem_adapter"}
pontem_adapter_v2 = {local = "./adapters/pontem_adapter_v2"}
pancake_adapter = {local = "./adapters/pancake_adapter"}
cellana_adapter = {local = "./adapters/cellana_adapter"}
hyperion_adapter = {local = "./adapters/hyperion_adapter"}


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = 'mainnet'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib/"
rev = 'mainnet'





