[package]
name = "dexrouter"
version = "2.0.1"

[addresses]
dexrouter = "0xd7ed3ceeb92c4e5a413e8ad7fab83ced12bf4141a49248a91b5485cb45a0ef4b"
deployer = "0x14b2864b0df3553a864dc8560925309ff05bde4dec5a731b54e6f3cee541ef91"

[dependencies]
pontem_adapter =  {local = "./adapters/pontem_adapter"}
pontem_adapter_v2 = {local = "./adapters/pontem_adapter_v2"}
pancake_adapter = {local = "./adapters/pancake_adapter"}
cellana_adapter = {local = "./adapters/cellana_adapter"}
hyperion_adapter = {local = "./adapters/hyperion_adapter"}


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = 'mainnet'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib/"
rev = 'mainnet'





