[package]
name = "econia_adapter"
version = "0.0.0"

[addresses]
econia_adapter = "cb95e54bf4baa46bfc6748ef979edca6199a923df3d0757d896a7dc93514a19b"

[dependencies]
# econia = "b1d4c0de8bc24468608637dfdbff975a0888f8935aa63338a44078eec5c7b6c7"
# Econia = { git = "https://github.com/manahip/econia.git", subdir = "src/move/econia", rev = "b118f1c2a1b5f7b8f446f88dc9ee489428f7b534" }
Econia = { local = "../../modules/econia" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = 'mainnet_aptos-cli-v1.0.0'