[package]
name = "hyperion_adapter"
version = "0.0.0"

[addresses]
hyperion_adapter = "0x7ea4a42a510899c9e303b1f896e6a1ea98909599c5b3b272e141b1957d02312b"

[dependencies]
dex = { local = "../../interface/hyperion" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = 'mainnet'