[package]
name = 'CoinList'
version = '0.0.0'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = 'mainnet_aptos-cli-v1.0.0'

[addresses]
coin_list = "b82e0420c4c10eacd5fae773dc6b53bfe84f5b03ae5af029057fe785ed70c91f"
