[package]
name = "uniswap_adapter"
version = "0.0.0"

# set 
[addresses]
uniswap_adapter = "cb95e54bf4baa46bfc6748ef979edca6199a923df3d0757d896a7dc93514a19b"


[dependencies]
uniswapv2 = { local = "../../modules/uniswap" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = 'mainnet_aptos-cli-v1.0.0'