[package]
name = "pontem-liquidswap-bridge_adapter"
version = "0.0.0"

[addresses]
pontem-liquidswap-bridge_adapter = "18c5af3d8794889112ae5665a684f79639a3a253ec6a87562ceb9ac99e1095dd"

[dependencies]
cbridge = { local = "../../interface/pontem-liquidswap-bridge" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = 'mainnet'